// Custom utility class rule
//
// The rule is a tuple of two objects: a matcher and a constructor.  For each
// rule the matcher checks wherever a token is an inline class and the
// constructor returns appropriate CSS.  A basic example is when both are strings:
//
// ```css
// /* ["backface-hidden", "backface-visibility: hidden;"]
// .backface-hidden { backface-visibility: hidden; }
// ```
//
// Regex can be used for more sophisticated matching:
//
// ```css
// /* [/object-\((.+)\)/, ([, prop]) => `object-position: var(${prop});`], */
// object-(--my-object) { object-position: var(--my-object) }
// ```
//
// Note that matching is done on "tokens", which are contiguous strings without
// whitespace (as matched by the `\s` regex class), apostrophes (`'`), quotes,
// or backticks.  Additionally, all prefixes which end in `:` will be stripped
// and matched against `State` rules.
export type Rule = [RegExp | string, ClassConstructor]
// See `Rule` documentation
export type ClassConstructor = string | ((matches: RegExpMatchArray) => string)

// A custom class state modifier
//
// These are used to implement conditionals such as `hover:`.  The generator
// tokenizer splits off prefixes which end in `:` from each token and match the
// first object in the state tuple against them.  A match is passed to
// `StateConstructor`.  See its documentation on how it works.
export type State = [RegExp | string, StateConstructor]
// A state constructor is a function which is passed the inner CSS generated by
// a custom class rule and the regex results from the matcher if there are any.
//
// Example implementation of `hover:`:
//
// ```css
// /* ["hover", css => `&:hover { @media (hover: hover) { ${css} } }`] */
// /* applied on hover:size-full */
// &:hover {
//   @media (hover: hover) {
//     .site-full { width: 100%; height: 100%; }
//   }
// }
// ```
export type StateConstructor = (
	css: string,
	matches: RegExpMatchArray,
) => string

// Options which can be resolved into `Config` with `defineConfig`
//
// The main difference is that options' properties are optional and it accepts
// `presets`, which will be merged recursively into the final `Config` object.
export type ConfigOptions = {
	rules?: Rule[]
	states?: State[]
	theme?: Record<string, string>
	base?: string
	// The contents of presets will be appended.  Presets are iterated in a
	// depth-first order.
	presets?: ConfigOptions[]
}

// Presets and custom settings for the `Generator` class
export type Config = {
	// Utility class rules
	//
	// These will be matched in the order they go in the list.  So, if two
	// rules could match a class, only the first one will be applied.
	rules: Rule[]
	// Matchers used for state prefixes such as `hover:`
	//
	// Their matching precedence logic is the same as for `rules`.
	states: State[]
	// CSS theme
	//
	// This is a collection of CSS variables and their values which will be put
	// into its own `theme` layer in the final output.
	theme: Record<string, string>
	// CSS which will be included verbatim in the output
	//
	// Currently used for resets.
	base: string
}

// Walks `ConfigOptions` and merges it and presets into a single `Config`
export function defineConfig(options: ConfigOptions): Config {
	const rules: Rule[] = []
	const states: State[] = []
	let theme = {}
	let base = ""

	function addPreset(preset: ConfigOptions): void {
		if (preset.rules) {
			rules.push(...preset.rules)
		}
		if (preset.states) {
			states.push(...preset.states)
		}
		if (preset.theme) {
			theme = { ...preset.theme, ...theme }
		}
		if (preset.base) {
			base = preset.base + base
		}
		if (preset.presets) {
			preset.presets.map(addPreset)
		}
	}

	addPreset(options)

	return {
		rules,
		states,
		theme,
		base,
	}
}
